name: Build & deploy snapshot

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build & deploy to Nexus
        env:
          NEXUS_USER: ci
          NEXUS_PASS: ${{ secrets.NEXUS_CI }}
        run: mvn -B --settings deploy.xml deploy
